# Use an official Node.js runtime as a parent image
FROM node:18 as builder

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Copy the rest of the application code to the working directory
COPY . .

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Install app dependencies
RUN npm cache clean --force
RUN npm install


# Build the Angular app
RUN ng build 

CMD ["ng", "serve", "--port", "80"]

# Expose port 80
EXPOSE 80


