# Stage 1: Use Ubuntu image to build Angular app
FROM ubuntu:20.04 as builder

# Set non-interactive mode during the build
ARG DEBIAN_FRONTEND=noninteractive

# Update the package lists and install required packages
RUN apt-get update && \
    apt-get install -y curl gnupg

# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_14.x | bash - && \
    apt-get install -y nodejs

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Create a directory for the app and set it as the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Angular app
RUN ng build --prod

# Stage 2: Use Nginx image to serve the Angular app
FROM nginx:alpine

# Set the working directory in Nginx
WORKDIR /usr/share/nginx/html

# Copy the built Angular app artifacts from the builder stage
COPY --from=builder /app/dist/test .

# Expose port 80
EXPOSE 80

# Start the nginx web server
CMD ["nginx", "-g", "daemon off;"]

