# Stage 1: Use Ubuntu image to build Angular app
FROM ubuntu:latest 

# Set non-interactive mode during the build

# Update the package lists and install required packages
RUN apt-get update && \
    apt-get install -y curl gnupg nginx 

# Install Node.js and npm
RUN curl -sL https://deb.nodesource.com/setup_18.x | bash - && \
    apt-get install -y nodejs 

# Install Angular CLI globally
RUN npm install -g @angular/cli

# Create a directory for the app and set it as the working directory
WORKDIR /app

# Copy package.json and package-lock.json to the working directory
COPY package*.json ./

# Install app dependencies
RUN npm install

# Copy the rest of the application code to the working directory
COPY . .

# Build the Angular app
RUN ng build 

RUN ls -la  dist/test
RUN cp dist/test/* /var/www/html/
# Copy the built Angular app artifacts from the builder stage
RUN cp dist/test/* /usr/share/nginx/html/ 

# Expose port 80
EXPOSE 80

# Start the nginx web server
CMD ["nginx", "-g", "daemon off;"]

